app = "bts-korean-website-optimized"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "30s"
  grace_period = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "15s"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
